import { defineConfig } from "vitest/config";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import path from "node:path";

export default defineConfig({
	plugins: [svelte({ hot: false })],
	resolve: {
		alias: {
			"$lib": path.resolve(__dirname, "src/lib"),
			"$app": path.resolve(__dirname, "src/test-stubs/$app"),
			// `$env/static/public` is a virtual module generated by the
			// SvelteKit Vite plugin at build time; under vitest we alias it
			// to a tiny stub that returns the value of
			// process.env.PUBLIC_STRIPE_PUBLISHABLE_KEY (or '' when unset).
			// This lets the StripeElementsLoader's real `$env/static/public`
			// import resolve in unit tests without spinning up the full
			// SvelteKit build pipeline.
			"$env/static/public": path.resolve(
				__dirname,
				"src/test-stubs/$env/static/public.ts",
			),
		},
	},
	test: {
		include: ["tests/**/*.test.ts"],
		exclude: ["node_modules", "dist", ".svelte-kit", "e2e/**"],
		environment: "node",
		globals: true,
		setupFiles: ["tests/setup/web-crypto-polyfill.ts"],
		testTimeout: 30000,
		hookTimeout: 10000,
		pool: "vmForks",
	},
});
