// @ts-nocheck

import { LOCALES } from './grids.mjs';

const ALL = [...LOCALES];
const LAND = LOCALES.filter((locale) => locale !== 'underwater' && locale !== 'space');

function prop(propId, label, localeAffinity = LAND) {
	return { propId, label, localeAffinity };
}

export const PROPS = [
	prop('lantern', 'warm paper lantern', ['forest', 'mountain', 'desert', 'meadow', 'farm', 'imaginary']),
	prop('picture-book', 'well-loved picture book', ALL),
	prop('red-wagon', 'small red wagon', ['urban', 'farm', 'meadow', 'forest']),
	prop('sandcastle', 'bucket-built sandcastle', ['seaside']),
	prop('sled', 'wooden snow sled', ['snowfield', 'mountain']),
	prop('kite', 'bright diamond kite', ['seaside', 'meadow', 'farm', 'urban']),
	prop('umbrella', 'round rain umbrella', ['urban', 'forest', 'seaside', 'jungle']),
	prop('teddy-bear', 'soft teddy bear', ALL),
	prop('fishing-rod', 'child-sized fishing rod', ['seaside', 'forest', 'mountain', 'farm']),
	prop('telescope', 'small brass telescope', ['space', 'mountain', 'urban', 'imaginary']),
	prop('compass', 'simple explorer compass', LAND),
	prop('map-scroll', 'curled treasure map', LAND),
	prop('magnifying-glass', 'round magnifying glass', LAND),
	prop('backpack', 'small adventure backpack', LAND),
	prop('watering-can', 'painted watering can', ['farm', 'meadow', 'forest', 'urban']),
	prop('seed-packet', 'packet of flower seeds', ['farm', 'meadow', 'urban', 'forest']),
	prop('basket', 'woven gathering basket', LAND),
	prop('blue-ball', 'bouncy blue ball', LAND),
	prop('wooden-blocks', 'stack of wooden blocks', ['urban', 'farm', 'meadow', 'imaginary']),
	prop('toy-train', 'wooden toy train', ['urban', 'farm', 'imaginary']),
	prop('drum', 'small hand drum', LAND),
	prop('xylophone', 'rainbow toy xylophone', LAND),
	prop('paintbrush', 'chunky paintbrush', LAND),
	prop('paint-palette', 'washable paint palette', LAND),
	prop('crayon-box', 'box of chunky crayons', ALL),
	prop('paper-crown', 'folded paper crown', ALL),
	prop('star-wand', 'glittery star wand', ['imaginary', 'urban', 'meadow', 'forest']),
	prop('ribbon-stick', 'dancing ribbon stick', LAND),
	prop('pinwheel', 'spinning pinwheel', ['seaside', 'meadow', 'farm', 'urban']),
	prop('bubble-wand', 'bubble wand', ['seaside', 'meadow', 'urban', 'farm']),
	prop('shell', 'spiral seashell', ['seaside', 'underwater']),
	prop('tidepool-bucket', 'small tidepool bucket', ['seaside']),
	prop('beach-ball', 'striped beach ball', ['seaside', 'underwater']),
	prop('sailboat-toy', 'tiny toy sailboat', ['seaside', 'underwater', 'imaginary']),
	prop('coral-charm', 'smooth coral-shaped charm', ['underwater', 'seaside']),
	prop('pearl-box', 'tiny pearl treasure box', ['underwater', 'seaside', 'imaginary']),
	prop('kelp-ribbon', 'floating kelp ribbon', ['underwater']),
	prop('snorkel-mask', 'child snorkel mask', ['underwater', 'seaside']),
	prop('moon-rock', 'smooth moon rock', ['space']),
	prop('rocket-toy', 'retro toy rocket', ['space', 'urban', 'imaginary']),
	prop('star-chart', 'folded star chart', ['space', 'mountain', 'urban']),
	prop('space-helmet', 'round toy space helmet', ['space']),
	prop('planet-mobile', 'hanging planet mobile', ['space', 'urban', 'imaginary']),
	prop('glow-star', 'glowing paper star', ['space', 'imaginary', 'urban']),
	prop('meteor-marble', 'swirled meteor marble', ['space', 'imaginary']),
	prop('gravity-boots', 'soft pretend gravity boots', ['space', 'imaginary']),
	prop('pinecone', 'large friendly pinecone', ['forest', 'mountain']),
	prop('acorn-cup', 'tiny acorn cup', ['forest', 'meadow']),
	prop('leaf-umbrella', 'broad leaf umbrella', ['forest', 'jungle', 'imaginary']),
	prop('birdhouse', 'small painted birdhouse', ['forest', 'farm', 'meadow', 'urban']),
	prop('mushroom-stool', 'storybook mushroom stool', ['forest', 'imaginary', 'jungle']),
	prop('wooden-bridge', 'miniature wooden bridge', ['forest', 'jungle', 'imaginary']),
	prop('trail-sign', 'friendly trail sign', ['forest', 'mountain', 'meadow']),
	prop('bug-jar', 'vented observation jar', ['forest', 'meadow', 'farm', 'jungle']),
	prop('climbing-rope', 'knotted climbing rope', ['mountain', 'forest', 'jungle']),
	prop('hiking-stick', 'smooth hiking stick', ['mountain', 'forest', 'meadow']),
	prop('wool-hat', 'cozy wool hat', ['mountain', 'snowfield', 'urban']),
	prop('thermos', 'small cocoa thermos', ['mountain', 'snowfield', 'farm']),
	prop('snow-globe', 'tiny snow globe', ['snowfield', 'urban', 'imaginary']),
	prop('mittens', 'pair of colorful mittens', ['snowfield', 'mountain', 'urban']),
	prop('snowflake-card', 'paper snowflake card', ['snowfield', 'urban', 'imaginary']),
	prop('ice-skates', 'child ice skates', ['snowfield']),
	prop('cactus-flower', 'blooming cactus flower', ['desert']),
	prop('sun-hat', 'wide sun hat', ['desert', 'farm', 'seaside', 'meadow']),
	prop('clay-cup', 'painted clay cup', ['desert', 'farm', 'imaginary']),
	prop('wind-chime', 'gentle wind chime', ['desert', 'farm', 'urban', 'meadow']),
	prop('shade-cloth', 'striped shade cloth', ['desert', 'seaside', 'farm']),
	prop('smooth-stone', 'smooth painted stone', LAND),
	prop('flower-crown', 'wildflower crown', ['meadow', 'farm', 'forest', 'imaginary']),
	prop('butterfly-net', 'soft butterfly net', ['meadow', 'farm', 'forest']),
	prop('picnic-blanket', 'checkered picnic blanket', ['meadow', 'farm', 'forest', 'urban']),
	prop('jam-jar', 'jar of berry jam', ['farm', 'meadow', 'forest']),
	prop('story-quilt', 'small patchwork quilt', ['farm', 'urban', 'meadow']),
	prop('apple-basket', 'basket of apples', ['farm', 'meadow']),
	prop('carrot-bundle', 'bundle of carrots', ['farm', 'meadow']),
	prop('milk-pail', 'small shiny milk pail', ['farm']),
	prop('scarecrow-hat', 'floppy scarecrow hat', ['farm', 'imaginary']),
	prop('tractor-toy', 'toy tractor', ['farm']),
	prop('city-bus-pass', 'pretend city bus pass', ['urban']),
	prop('chalk', 'sidewalk chalk pieces', ['urban', 'farm']),
	prop('mailbox-key', 'oversized mailbox key', ['urban', 'farm', 'imaginary']),
	prop('library-card', 'first library card', ['urban']),
	prop('crosswalk-flag', 'small crosswalk safety flag', ['urban']),
	prop('sketchbook', 'pocket sketchbook', ALL),
	prop('lunchbox', 'bright lunchbox', ['urban', 'farm', 'meadow']),
	prop('jungle-vine-swing', 'soft vine swing', ['jungle', 'imaginary']),
	prop('rainstick', 'painted rainstick', ['jungle', 'desert', 'forest']),
	prop('banana-leaf-fan', 'banana leaf fan', ['jungle']),
	prop('orchid-bloom', 'large orchid bloom', ['jungle']),
	prop('seed-pod-rattle', 'seed pod rattle', ['jungle', 'forest']),
	prop('storybook-key', 'ornate storybook key', ['imaginary', 'urban', 'forest']),
	prop('cloud-pillow', 'puffy cloud pillow', ['imaginary', 'space']),
	prop('rainbow-bridge-token', 'rainbow bridge token', ['imaginary']),
	prop('tiny-door', 'tiny round door', ['imaginary', 'forest']),
	prop('clockwork-bird', 'clockwork bird toy', ['imaginary', 'urban']),
	prop('floating-teacup', 'floating pretend teacup', ['imaginary']),
	prop('friendship-bracelet', 'woven friendship bracelet', ALL),
	prop('thank-you-card', 'handmade thank-you card', ALL),
	prop('lost-button', 'shiny lost button', ALL),
	prop('tiny-bell', 'tiny silver bell', ALL),
	prop('soft-scarf', 'soft striped scarf', LAND),
	prop('family-photo-frame', 'empty family photo frame', ['urban', 'farm', 'meadow', 'imaginary']),
];
