// vitest stub for SvelteKit's `$env/static/public` virtual module.
//
// In a real Svelte build, `$env/static/public` is statically generated by
// the SvelteKit Vite plugin at build time, sourcing `PUBLIC_*`-prefixed
// env vars from `.env`/`.env.local`/runtime env. Under vitest this plugin
// is not active, so the import would fail at module-load. This stub
// returns the value of `process.env.PUBLIC_STRIPE_PUBLISHABLE_KEY` (so
// tests can set it via `process.env.X = '...'` in `beforeEach`) and
// defaults to `''` when unset — matching the SvelteKit shape exactly.
//
// The stub is wired by `vitest.config.ts::resolve.alias` so any test that
// imports `import { PUBLIC_STRIPE_PUBLISHABLE_KEY } from '$env/static/public'`
// transparently picks it up.

export const PUBLIC_STRIPE_PUBLISHABLE_KEY: string =
	(typeof process !== 'undefined' && process.env?.PUBLIC_STRIPE_PUBLISHABLE_KEY) || '';
