// @graph-layer: private
// @rationale: private (per-user / per-settler state — never leaves device by default)

// src/lib/services/PillarManifestClient.ts
//
// Fetches the World Builder pillar-library manifest once per session,
// caches in a module-scoped variable, validates the wire shape, converts
// inbound `number[]` embeddings to Float32Array.
//
// Spec: docs/specs/2026-05-24-design.md §3.2
// ADR:  docs/adr/0043 — only opaque integer `pillarId` ever leaves the
//        device; the manifest itself is anonymous, public, CDN-cacheable.
//
// Why module-scoped (not class-scoped) cache: the manifest is genuinely
// process-wide singleton state — every workshop session in the same tab
// reads the same upstream catalog. Class-scoping would invite confusion
// about "which instance has the cache." The trade-off (one global mutable
// ref) is acceptable because the cache is immutable per-fetch and
// invalidate() is the only mutator.
//
// Fallback chain
// --------------
// Real Pixal3D-baked CDN manifest is deferred per ADR-0044 / goal
// 2026-05-25-pillar-library-pixal3d.md. To keep Station 2 useful today,
// fetchManifest() walks:
//
//   1. PRIMARY     → /api/world/pillar-library/manifest   (real WB upstream)
//   2. PILLAR-V2  → /pillar-library-v2/manifest.json  (150-archetype static bake with portrait thumbs)
//   3. PLACEHOLDER → /pillar-library-v1-placeholder/manifest.json  (legacy 50-entry static)
//   3. EMPTY       → []  (logs a warn; workshop UI surfaces "library unavailable")
//
// The placeholder static asset is generated by
// `scripts/pillar-library/generate-placeholders.mjs` (50 entries; deterministic).
// Each fallback hop logs an info-level reason so /debug surfaces don't
// have to guess. Step (2) carries a `urls` field on each entry pointing
// at the per-pillar preview/front/back/left/right asset paths — extra
// fields are ignored by parseManifest, so the legacy 3-field (no urls)
// shape from a real WB upstream remains compatible.

import type { Pillar, PillarAxes, PillarManifestEntry } from './types';

const PRIMARY_MANIFEST_URL = '/api/world/pillar-library/manifest';
const PLACEHOLDER_MANIFEST_URL = '/pillar-library-v1-placeholder/manifest.json';
const V2_MANIFEST_URL = '/pillar-library-v2/manifest.json';

/**
 * Source from which the current cache was populated. Useful for debug
 * surfaces and tests that need to assert the fallback chain walked.
 */
export type PillarManifestSource = 'primary' | 'pillar-library-v2' | 'placeholder' | 'empty';

/** Module-scoped session cache. Cleared via `invalidate()`. */
let _cache: Pillar[] | null = null;
let _cacheSource: PillarManifestSource | null = null;
let _inflight: Promise<Pillar[]> | null = null;

/** Test-injection hook for the fetcher (so vitest doesn't need a real network). */
let _fetchOverride:
    | ((url: string) => Promise<Response>)
    | null = null;

/**
 * Try a single manifest URL. Returns `null` (with a warn) when the
 * endpoint is unreachable or the payload is malformed — the caller then
 * walks to the next step in the fallback chain.
 */
async function _tryFetchOne(
    fetcher: (url: string) => Promise<Response>,
    url: string,
    sourceLabel: PillarManifestSource,
): Promise<Pillar[] | null> {
    try {
        const res = await fetcher(url);
        if (!res.ok) {
            console.warn(
                `[PillarManifestClient] ${sourceLabel} fetch ${res.status} ${res.statusText} (${url}); trying next source`,
            );
            return null;
        }
        const raw = await res.json();
        return parseManifest(raw);
    } catch (err) {
        console.warn(
            `[PillarManifestClient] ${sourceLabel} fetch threw (${url}); trying next source:`,
            err,
        );
        return null;
    }
}

/**
 * One-shot fetch + cache. Subsequent callers within a session get the
 * cached array. `invalidate()` forces a re-fetch on next call.
 *
 * Walks the primary → placeholder → empty fallback chain (see file
 * header). Always resolves (never throws) — the workshop UI treats an
 * empty array as "library unavailable" rather than crashing.
 */
export async function fetchManifest(): Promise<Pillar[]> {
    if (_cache) return _cache;
    if (_inflight) return _inflight;

    _inflight = (async (): Promise<Pillar[]> => {
        try {
            const fetcher =
                _fetchOverride ??
                (typeof fetch !== 'undefined' ? fetch : null);
            if (!fetcher) {
                console.warn(
                    '[PillarManifestClient] no fetch available; returning empty manifest',
                );
                _cache = [];
                _cacheSource = 'empty';
                return _cache;
            }

            // 1. Real WB upstream
            const primary = await _tryFetchOne(
                fetcher,
                PRIMARY_MANIFEST_URL,
                'primary',
            );
            if (primary && primary.length > 0) {
                _cache = primary;
                _cacheSource = 'primary';
                return primary;
            }

            // 2. Pillar-library v2 — 150-archetype static bake with portrait thumbs
            const v2 = await _tryFetchOne(
                fetcher,
                V2_MANIFEST_URL,
                'pillar-library-v2',
            );
            if (v2 && v2.length > 0) {
                console.info(
                    `[PillarManifestClient] using pillar-library-v2 (${v2.length} archetypes with portrait thumbs).`,
                );
                _cache = v2;
                _cacheSource = 'pillar-library-v2';
                return v2;
            }

            // 3. Local v1 placeholder static asset (legacy 50-entry)
            const placeholder = await _tryFetchOne(
                fetcher,
                PLACEHOLDER_MANIFEST_URL,
                'placeholder',
            );
            if (placeholder && placeholder.length > 0) {
                console.info(
                    `[PillarManifestClient] using placeholder library (${placeholder.length} pillars). Real Pixal3D bake deferred.`,
                );
                _cache = placeholder;
                _cacheSource = 'placeholder';
                return placeholder;
            }

            // 4. Empty (workshop UI surfaces "library unavailable")
            console.warn(
                '[PillarManifestClient] all manifest sources empty/unreachable; returning []',
            );
            _cache = [];
            _cacheSource = 'empty';
            return _cache;
        } finally {
            _inflight = null;
        }
    })();

    return _inflight;
}

/**
 * Clear the session cache. Next `fetchManifest()` call re-issues the
 * network request. Used by the workshop's "refresh pillar library"
 * admin debug action and by vitest between specs.
 */
export function invalidate(): void {
    _cache = null;
    _cacheSource = null;
    _inflight = null;
}

/**
 * Synchronous accessor — returns the cached array (or `null` if not yet
 * fetched). Useful for UI components that want to render immediately if
 * the cache is warm without awaiting.
 */
export function getCachedManifest(): Pillar[] | null {
    return _cache;
}

/**
 * Synchronous accessor for the source of the current cache. Returns
 * `null` if `fetchManifest()` hasn't completed yet.
 */
export function getCachedManifestSource(): PillarManifestSource | null {
    return _cacheSource;
}

/**
 * Validate + convert the JSON payload into the strongly-typed `Pillar[]`
 * shape. Drops any entry whose shape is malformed (with a warn) rather
 * than throwing — one bad entry shouldn't take down the whole library.
 *
 * Top-level shape: `Pillar[]` (the endpoint returns an array, not an
 * object — keeps the JSON small and the parser simple).
 *
 * Extra fields on each entry (e.g. `urls`) are tolerated and dropped
 * (the matcher cares only about pillarId + axes + embedding).
 */
export function parseManifest(raw: unknown): Pillar[] {
    if (!Array.isArray(raw)) {
        throw new Error(
            `PillarManifestClient: expected top-level array, got ${typeof raw}`,
        );
    }
    const out: Pillar[] = [];
    for (let i = 0; i < raw.length; i++) {
        const entry = raw[i] as Partial<PillarManifestEntry>;
        if (!entry || typeof entry !== 'object') {
            console.warn(
                `[PillarManifestClient] entry ${i} not an object; skipping`,
            );
            continue;
        }
        if (typeof entry.pillarId !== 'number' || !Number.isFinite(entry.pillarId)) {
            console.warn(
                `[PillarManifestClient] entry ${i} missing/invalid pillarId; skipping`,
            );
            continue;
        }
        if (!entry.axes || !_isPillarAxes(entry.axes)) {
            console.warn(
                `[PillarManifestClient] entry ${i} (pillarId ${entry.pillarId}) missing/invalid axes; skipping`,
            );
            continue;
        }
        if (!Array.isArray(entry.embedding) || entry.embedding.length === 0) {
            console.warn(
                `[PillarManifestClient] entry ${i} (pillarId ${entry.pillarId}) missing/empty embedding; skipping`,
            );
            continue;
        }
        const emb = new Float32Array(entry.embedding.length);
        let ok = true;
        for (let j = 0; j < entry.embedding.length; j++) {
            const v = entry.embedding[j];
            if (typeof v !== 'number' || !Number.isFinite(v)) {
                ok = false;
                break;
            }
            emb[j] = v;
        }
        if (!ok) {
            console.warn(
                `[PillarManifestClient] entry ${i} (pillarId ${entry.pillarId}) non-finite embedding value; skipping`,
            );
            continue;
        }
        out.push({
            pillarId: entry.pillarId,
            axes: entry.axes,
            embedding: emb,
        });
    }
    return out;
}

function _isPillarAxes(x: unknown): x is PillarAxes {
    if (!x || typeof x !== 'object') return false;
    const o = x as Record<string, unknown>;
    return (
        typeof o.hair === 'string' &&
        typeof o.skinTone === 'string' &&
        typeof o.eyeColor === 'string' &&
        typeof o.ageBand === 'string' &&
        typeof o.clothingVibe === 'string' &&
        Array.isArray(o.extras)
    );
}

/** Test-only surface. */
export const __test = {
    setFetchOverride(fn: ((url: string) => Promise<Response>) | null): void {
        _fetchOverride = fn;
    },
    reset(): void {
        _cache = null;
        _cacheSource = null;
        _inflight = null;
        _fetchOverride = null;
    },
    getCache(): Pillar[] | null {
        return _cache;
    },
    getCacheSource(): PillarManifestSource | null {
        return _cacheSource;
    },
};
